### ISSUE TITLE
 could not find "Matrix6d"

### ISSUE THREAD

**Issue by dongpan90** [chuanstudyup/MPU9250#1]
I encountered some problems when compiling the source code. Can you open the complete compilation project。
for example, i could not find "Matrix6d".

**Comment by chuanstudyup** [comment]
You may add

typedef Matrix<double, 6, 6> Matrix6d;

in the head of QuaternionFilter.h

**Comment by chuanstudyup** [comment]
> I encountered some problems when compiling the source code. Can you open the complete compilation project。 for example, i could not find "Matrix6d".

**Comment by chuanstudyup** [comment]
You may add

typedef Matrix<double, 6, 6> Matrix6d;

in the head of QuaternionFilter.h

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年11月26日 16:44
收件人: ***@***.***>
抄送: ***@***.***>
主题: [chuanstudyup/MPU9250] could not find "Matrix6d" (Issue #1)


I encountered some problems when compiling the source code. Can you open the complete compilation project。
for example, i could not find "Matrix6d".

―
